name = "mosques-in-oman"
main = "src/index.ts"
compatibility_date = "2024-02-28"

[vars]
ENVIRONMENT = "development"



[[d1_databases]]
binding = "DB"
database_name = "mosquesdb"
database_id = "a775b65a-62ad-4439-8e89-8db072cbd01b"


